package(default_visibility = ["//visibility:public"])

cc_test(
    name = "sudoku_solver_test",
    srcs = ["sudoku_solver_test.cc"],
    linkstatic = True,
    deps = ["@com_google_googletest//:gtest_main"],
)
