package(default_visibility = ["//visibility:public"])

cc_test(
    name = "cherry_pickup_test",
    srcs = ["cherry_pickup_test.cc"],
    linkstatic = True,
    deps = ["@com_google_googletest//:gtest_main"],
)
