package(default_visibility = ["//visibility:public"])

cc_test(
    name = "longest_valid_parentheses_test",
    srcs = ["longest_valid_parentheses_test.cc"],
    linkstatic = True,
    deps = ["@com_google_googletest//:gtest_main"],
)
