package(default_visibility = ["//visibility:public"])

cc_test(
    name = "max_dot_product_test",
    srcs = ["max_dot_product_test.cc"],
    linkstatic = True,
    deps = ["@com_google_googletest//:gtest_main"],
)
